name: Create and Upload Artifact

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: install pnpm
        run: npm install -g pnpm
      - name: install dependencies
        run: pnpm install
      - name: build site
        env:
          VERCEL: 1
        run: pnpm build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vercel
          path: .vercel
