name: Create and Upload Artifact

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  do-thing:
    name: "test-python-${{ matrix.os }}-${{ matrix.test-type == 'flaky' && 'flaky' || 'not-flaky'}}"
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        test-type: ["not flaky", "flaky"]
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJson(github) }}'
  create-artifact:
    runs-on: ubuntu-latest
    needs: do-thing
    if: github.event_name == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-dir
          path: dir/subdir
