name: Create and Upload Artifact

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-dir
          path: dir/subdir
