name: Download and Cat Artifact

on:
  workflow_run:
    workflows: ["Create and Upload Artifact"]
    types:
      - completed

permissions:
  actions: read

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vercel
          path: js/website/.vercel
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Cat artifact
        run: ls -Ra .
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: install vercel cli
        run: npm install -g vercel
      - name: pull vercel project
        run: vercel pull --token ${{ secrets.VERCEL }} --yes
      - name: deploy site
        run: vercel deploy --prebuilt --token ${{ secrets.VERCEL }} --yes --cwd js/website
