name: Download and Cat Artifact

on:
  workflow_run:
    workflows: ["Create and Upload Artifact"]
    types:
      - completed

permissions:
  actions: read

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-dir
          path: different_dir
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: list files
        run: ls -R different_dir
      - name: cat file
        run: cat different_dir/four.txt
