name: test json

on:
  pull_request:
    branches:
    - main


jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
      - uses: gradio-app/github/actions/input-to-json@main
        with:
          path: output.json
          one: "hello"
          two: "hello again"
          "nested.one": "hello nested"
          "nested.two": "hello again nested"
      - run: cat output.json
      - uses: gradio-app/github/actions/json-to-output@main
        id: json
        with:
          path: output.json
      - run: echo "${{ toJson(steps.json.outputs) }}"
      
