name: Download and Cat Artifact

on:
  workflow_run:
    workflows: ["Create and Upload Artifact"]
    types:
      - completed
      
permissions: 
  actions: read

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: sample-artifact
          path: sample_file.txt

      - name: Cat file content
        run: cat artifact-download/sample_file.txt
